# Generated by Django 2.1.4 on 2019-01-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='realtor_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
