# Generated by Django 2.1.4 on 2019-01-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_realtor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='realtor_id',
        ),
    ]
